export type Lang = "tr" | "en";

const translations = {
  tr: {
    appTagline: "Yapay zeka ile notlarını özetle ve kendini test et.",
    newNote: "← Yeni Not",
    tabSummary: "Ders Özeti",
    tabQuiz: "Anlama Testi",

    // NoteInput
    inputLabel: "Ders Notlarınızı Buraya Yapıştırın",
    inputPlaceholder: "Örn: Hücre biyolojisi hakkında aldığım notlar...",
    inputOverLimit: (max: number) => `Not çok uzun. ${max} karakteri aşmayın.`,
    btnAnalyze: "Notları Analiz Et ve Quiz Oluştur",
    btnLoading: "İşleniyor...",
    btnCooldown: (s: number) => `Lütfen bekle (${s}s)`,

    // SummaryCard
    btnCopy: "Kopyala",
    btnCopied: "Kopyalandı",
    btnPrint: "PDF / Yazdır",
    sectionOverview: "Genel Bakış",
    sectionKeyPoints: "Ana Fikirler",
    sectionTerms: "Önemli Kavramlar",
    termHint: "Tanım için tıkla",
    btnGoToQuiz: "Kendini Test Et",
    printTitle: "Ders Özeti",
    copyOverview: "GENEL BAKIŞ",
    copyKeyPoints: "ANA FİKİRLER",
    copyTerms: "ÖNEMLİ KAVRAMLAR",

    // QuizModule
    quizTitle: "Anlama Testi",
    quizComplete: "Quiz Tamamlandı",
    quizCorrectLabel: "Doğru",
    quizTotalLabel: "Toplam",
    quizCorrectAnswer: "Doğru cevap:",
    btnRestart: "Yeniden Başla",
    btnNext: "Sonraki Soru",
    btnSeeResults: "Sonuçları Gör",
    scoreMessages: [
      { minPct: 1.0, text: "Mükemmel! Konuya tam hakimsin.", color: "text-emerald-400" },
      { minPct: 0.8, text: "Çok iyi! Küçük eksikler var.", color: "text-indigo-400" },
      { minPct: 0.6, text: "İyi gidiyorsun, biraz daha çalış.", color: "text-amber-400" },
      { minPct: 0, text: "Konuyu tekrar gözden geçir.", color: "text-rose-400" },
    ],

    // EthicalWarning
    ethicalWarning:
      "Bu özet ve sorular Yapay Zeka tarafından üretilmiştir, lütfen doğruluklarını notlarınızdan teyit ediniz.",

    // HistoryPanel
    historyTitle: "Geçmiş Analizler",
    historyLoadTitle: "Yükle",
    historyDeleteTitle: "Sil",

    // Errors
    errorEmpty: "Not içeriği boş olamaz.",
    errorTooLong: (max: number) => `Not çok uzun. Maksimum ${max} karakter girilebilir.`,
    errorParse: "Yapay zeka yanıtı işlenirken bir hata oluştu.",
    errorApi: (msg: string) => `API çağrısı sırasında bir hata oluştu: ${msg}`,
    errorGeneric: "Bir hata oluştu.",
  },
  en: {
    appTagline: "Summarize your notes and test yourself with AI.",
    newNote: "← New Note",
    tabSummary: "Summary",
    tabQuiz: "Quiz",

    // NoteInput
    inputLabel: "Paste Your Lecture Notes Here",
    inputPlaceholder: "E.g. My notes on cell biology...",
    inputOverLimit: (max: number) => `Note is too long. Stay under ${max} characters.`,
    btnAnalyze: "Analyze Notes & Generate Quiz",
    btnLoading: "Processing...",
    btnCooldown: (s: number) => `Please wait (${s}s)`,

    // SummaryCard
    btnCopy: "Copy",
    btnCopied: "Copied",
    btnPrint: "PDF / Print",
    sectionOverview: "Overview",
    sectionKeyPoints: "Key Points",
    sectionTerms: "Important Terms",
    termHint: "Click for definition",
    btnGoToQuiz: "Test Yourself",
    printTitle: "Lecture Summary",
    copyOverview: "OVERVIEW",
    copyKeyPoints: "KEY POINTS",
    copyTerms: "IMPORTANT TERMS",

    // QuizModule
    quizTitle: "Comprehension Quiz",
    quizComplete: "Quiz Complete",
    quizCorrectLabel: "Correct",
    quizTotalLabel: "Total",
    quizCorrectAnswer: "Correct answer:",
    btnRestart: "Restart",
    btnNext: "Next Question",
    btnSeeResults: "See Results",
    scoreMessages: [
      { minPct: 1.0, text: "Perfect! You've mastered this topic.", color: "text-emerald-400" },
      { minPct: 0.8, text: "Great job! Just a few gaps remain.", color: "text-indigo-400" },
      { minPct: 0.6, text: "Good progress, keep studying.", color: "text-amber-400" },
      { minPct: 0, text: "Review the topic again.", color: "text-rose-400" },
    ],

    // EthicalWarning
    ethicalWarning:
      "This summary and questions were generated by AI. Please verify their accuracy against your original notes.",

    // HistoryPanel
    historyTitle: "Past Analyses",
    historyLoadTitle: "Load",
    historyDeleteTitle: "Delete",

    // Errors
    errorEmpty: "Note content cannot be empty.",
    errorTooLong: (max: number) => `Note is too long. Maximum ${max} characters allowed.`,
    errorParse: "An error occurred while processing the AI response.",
    errorApi: (msg: string) => `An error occurred during the API call: ${msg}`,
    errorGeneric: "An error occurred.",
  },
} as const;

export type Translations = typeof translations.tr;
export default translations;
